import axios from "axios";
import { CreateStock } from "../Interfaces/interfaceStock";

export const postStock = async (obj:CreateStock) => {
    try{
        let post = await axios.post('/stock', obj);
        return post.data;
    }catch(err){
        console.log(`Error en postStock utils :${err}`);
    }
}

const StockTemplate = {
    _id:'',
    name:'',
    stock:[
        [{
          negro:{
            code:'#000000',
            stock_negro:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          blanco:{
            code:'#000000',
            stock_blanco:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          beige:{
            code:'#000000',
            stock_beige:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          gris:{
            code:'#000000',
            stock_gris:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          azul_francia:{
            code:'#000000',
            stock_azul_francia:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          azul_marino:{
            code:'#000000',
            stock_azul_marino:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          azul:{
            code:'#000000',
            stock_azul:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          plata:{
            code:'#000000',
            stock_plata:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          tiza:{
            code:'#000000',
            stock_tiza:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          amarillo:{
            code:'#000000',
            stock_amarillo:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          dorado:{
            code:'#000000',
            stock_dorado:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          marron:{
            code:'#000000',
            stock_marron:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          marron_havana:{
            code:'#000000',
            stock_marron_havana:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          marron_suela:{
            code:'#000000',
            stock_marron_suela:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          marron_cafe:{
            code:'#000000',
            stock_marron_cafe:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          bordo:{
            code:'#000000',
            stock_bordo:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          rojo:{
            code:'#000000',
            stock_rojo:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          verde:{
            code:'#000000',
            stock_verde:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          verde_oscuro:{
            code:'#000000',
            stock_verde_oscuro:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          verde_claro:{
            code:'#000000',
            stock_verde_claro:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          verde_menta:{
            code:'#000000',
            stock_verde_menta:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          verde_oliva:{
            code:'#000000',
            stock_verde_oliva:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          cereza:{
            code:'#000000',
            stock_cereza:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          fucsia:{
            code:'#000000',
            stock_fucsia:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          morado:{
            code:'#000000',
            stock_morado:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          cobre:{
            code:'#000000',
            stock_cobre:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          camel:{
            code:'#000000',
            stock_camel:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          turquesa:{
            code:'#000000',
            stock_turquesa:0,
            xs:0,
            s:0,
            m:0,
            l:0,
            xl:0,
            xxl:0
          },
        }],
        [{
          all:0
        }]
      ]
}